### ISSUE TITLE
Problem while adding payment to order

### ISSUE THREAD

**Issue by 1blankz7** [commercetools/commercetools-dotnet-core-sdk#156]
We have a problem adding a new payment to an existing order.

Given the following code will result in a `ArgumentException` while trying to add an `OrderEditDraft`. 

```C#
var payment = await _client.ExecuteAsync(new CreateCommand<Payment>(paymentDraft));
OrderUpdateAction paymentUpdateAction = new AddPaymentUpdateAction {
    Payment = new Reference<Payment> {Id = payment.Id, Obj = payment}
};
actions.Add(paymentUpdateAction);

var orderEditDraft = new OrderEditDraft {
    Resource = new Reference<commercetools.Sdk.Domain.Orders.Order> {
        d = p.Order.Id,
        Obj = p.Order
    },
    StagedActions = actions
};

var orderEdit = await _client.ExecuteAsync(new CreateCommand<OrderEdit>(orderEditDraft)); // <- EXCEPTION HERE
await _client.ExecuteAsync(new ApplyOrderEditCommand(orderEdit, p.Order.Version));
```
We got the following stack trace:
```
System.ArgumentException: The value "commercetools.Sdk.Domain.Messages.GeneralMessage" is not of type "commercetools.Sdk.Domain.Messages.Message`1[commercetools.Sdk.Domain.Orders.Order]" and cannot be used in this generic collection. (Parameter 'value')
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at commercetools.Sdk.Serialization.JsonConverterDecoratorTypeRetrieverBase`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at commercetools.Sdk.Serialization.SerializerService.Deserialize[T](String input)
   at commercetools.Sdk.HttpApi.CtpClient.SendRequest[T](HttpRequestMessage requestMessage)
   at commercetools.Sdk.HttpApi.CtpClient.ExecuteAsync[T](ICommand`1 command)
```
The response from `/orders/edits/` comes back but we don't know why it behaves like that.

We use version 1.0.2 of the SDK.

Do we have a conceptual error? 

Thanks in advance.

**Comment by jenschude** [comment]
Could you please try with the version 1.0.4? As this was about a forward compabitility issue with messages in OrderEdits and it seems that you are experiencing exactly this issue.

**Comment by 1blankz7** [comment]
Thank you very much. This solved our issue.
