### ISSUE TITLE
ExpandDiscountCodes method does not work

### ISSUE THREAD

**Issue by skalovigor** [commercetools/commercetools-dotnet-core-sdk#159]
ExpandDiscountCodes method raise an exception:

` An unhandled exception was thrown by the application.
System.NotSupportedException: The method call is not supported in this expression.
   at commercetools.Sdk.Linq.ExpansionExpressionVisitor.GetMethod(MethodCallExpression expression)
   at commercetools.Sdk.Linq.ExpansionExpressionVisitor.GetPath(Expression expression)
   at commercetools.Sdk.Linq.ExpansionExpressionVisitor.GetMember(MemberExpression expression)
   at commercetools.Sdk.Linq.ExpansionExpressionVisitor.GetPath(Expression expression)
   at commercetools.Sdk.Linq.ExpansionExpressionVisitor.GetPath(Expression expression)
   at commercetools.Sdk.Linq.ExpressionRenderExtensions.RenderExpand(Expression expression)
   at commercetools.Sdk.Domain.Query.Expansion1.ToString()
   at commercetools.Sdk.Client.QueryCommandExtensions.Expand[T](QueryCommand`1 command, Expression`1 expression)`

I guess it is because of missing mapping in expandMethodMapping in ExpansionExpressionVisitor class
`private IDictionary<string, string> expandMethodMapping = new Dictionary<string, string>()
        {
            { "ExpandAll", "[*]" },
            { "ExpandProductSlugs", "[*].productSlug" },
            { "ExpandVariants", "[*].variant" },
            { "ExpandValues", "[*].value" }
        };`

**Comment by skalovigor** [comment]
Hi @jenschude 

Please add this mapping: `{ "ExpandDiscountCodes", "[*].discountCode" }`

Test:
`[Fact]
        public void ExpandOrderDiscountCodes()
        {
            Expression<Func<Order, Reference>> expression = l => l.DiscountCodes.ExpandDiscountCodes();
            ExpansionExpressionVisitor expansionVisitor = new ExpansionExpressionVisitor();
            string result = expansionVisitor.GetPath(expression);
            Assert.Equal("discountCodes[*].discountCode", result);
        }`

Thanks
Ihor

**Comment by skalovigor** [comment]
@jenschude any news on this?

**Comment by MicheleRezk** [comment]
@skalovigor We solved it and created a new release with version 1.1.1
