### ISSUE TITLE
Failure to fetch cart discounts due to deserialization error

### ISSUE THREAD

**Issue by FredrikEastman** [commercetools/commercetools-dotnet-core-sdk#170]
**Describe the bug**
When fetching cart discount of type `FIXED` the deserialization of the discount fails. 
I understand that the fixed discount is BETA but it's quite easy for the customers so add these anyway in the merchantcenter (it's also stated as new and not BETA there). 

**To Reproduce**
1. Create a fixed price discount. 
2. Fetch all cartdiscounts
3. Verify deserialization fails and you get an error message like the one below. 

```
[System.AggregateException: One or more errors occurred. (Couldn't get type to deserialize property type)
 ---> Newtonsoft.Json.JsonSerializationException: Couldn't get type to deserialize property type
   at commercetools.Sdk.Serialization.JsonConverterDecoratorTypeRetrieverBase`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at commercetools.Sdk.Serialization.SerializerService.Deserialize[T](Stream input)
   at commercetools.Sdk.HttpApi.CtpClient.SendRequest[T](HttpRequestMessage requestMessage)
   at commercetools.Sdk.HttpApi.CtpClient.ExecuteAsync[T](ICommand`1 command)](url)
```

**Expected behavior**
Do not throw deserialization error - return discount list without the failed discount. 

**Screenshots/Code snippet**
Problem caused while running: `client.Builder().CartDiscounts().Query().ExecuteAsync();`

**Stack information (please complete the following information):**
 - dotnet: CORE 2.1
 - SDK: v1.1.2

**Additional context**

**Comment by MicheleRezk** [comment]
@FredrikEastman We solved it and created a new release with version 1.1.3

**Comment by FredrikEastman** [comment]
@MicheleRezk Perfect, thank you very much!
